version: "3"

services:
 postgres:
   restart: always
   image: postgres:13
   environment:
     POSTGRES_USER: openoversight
     POSTGRES_PASSWORD: terriblepassword
     POSTGRES_DB: openoversight-dev
   volumes:
     - postgres:/var/lib/postgresql/data
   ports:
     - "5432:5432"

 web:
   restart: always
   build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
   env_file:
     - .env
   environment:
     FLASK_APP: app
     FLASK_ENV: "${FLASK_ENV:-development}"
   volumes:
     - ./OpenOversight/:/usr/src/app/OpenOversight/:z
     - ./data:/data/
   links:
     - postgres:postgres
   expose:
     - "3000"
   command: scripts/entrypoint.sh
   ports:
     - "3000:3000"
   networks:
     - protonmail
     - default

volumes:
  postgres:
    driver: local

networks:
  protonmail:
    external: True

