version: "3.2"

services:
  web:
    build:
      context: .
      args:
        IS_PROD: "true"
    environment:
      ENV: production
    volumes:
      - static_files:/usr/src/app/OpenOversight/static
    ports:
      - "3005:3000"
    networks:
      - protonmail
      - default

volumes:
  static_files:
    name: openoversight-static

networks:
  protonmail:
    external: True
