version: "3"

volumes:
  postgres:
    driver: local

services:
 postgres:
   restart: always
   image: postgres:13
   environment:
     POSTGRES_USER: openoversight
     POSTGRES_PASSWORD: terriblepassword
     POSTGRES_DB: openoversight-dev
   volumes:
     - postgres:/var/lib/postgresql/data
   ports:
     - "5432:5432"

 web:
   restart: always
   build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
   env_file:
     - .env
   environment:
     DOCKER_BUILD_ENV: "${DOCKER_BUILD_ENV}"
     AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
     AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
     AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
     S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
     APPROVE_REGISTRATIONS: "${APPROVE_REGISTRATIONS}"
     FLASK_APP: app
     FLASK_ENV: "${FLASK_ENV:-development}"
   volumes:
     - ./OpenOversight/:/usr/src/app/OpenOversight/:z
   links:
     - postgres:postgres
   expose:
     - "3000"
   command: scripts/entrypoint.sh
   ports:
     - "3000:3000"
