version: "3.2"

services:
  postgres:
    restart: always
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: openoversight
      POSTGRES_DB: openoversight
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    restart: always
    depends_on:
      - postgres
    image: ghcr.io/orcacollective/openoversight:${DB_IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      FLASK_APP: OpenOversight.app
      # Update with your application's respective Olson-style timezone:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#list
      TIMEZONE: "America/Chicago"
    volumes:
      - ./data:/data/
    secrets:
      - source: service-account-key
        target: /usr/src/app/service_account_key.json
    command: OpenOversight/scripts/entrypoint.sh

volumes:
  postgres:

secrets:
  service-account-key:
    file: ./service_account_key.json
