version: "3"

services:
  postgres:
    restart: always
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: openoversight
      POSTGRES_DB: openoversight
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    restart: always
    depends_on:
      - postgres
    image: ghcr.io/orcacollective/openoversight:${DB_IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      FLASK_APP: app
    volumes:
      - ./data:/data/
    command: scripts/entrypoint.sh
    ports:
      - "3000:3000"

volumes:
  postgres:
