name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Run tests
        run: |
          just build
          just up
          just test
