name: Lint and Test

on: pull_request

jobs:

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  tests:
    runs-on: ubuntu-latest
    needs: static-checks
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Run tests
        run: |
          just build
          just down -v
          just up
          sleep 3
          just test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: build/test-results/
      - if: ${{ failure() }}
        name: Print logs
        run: |
          echo "Minio logs:"
          docker compose logs minio || true
          echo "Createbucket logs:"
          docker compose logs createbucket || true
          echo "Postgres logs:"
          docker compose logs postgres || true
